from unittest_reinvent.scoring_tests.clab_models.test_pip_with_parallel_additive import Test_pip_with_parallel_additive
from unittest_reinvent.scoring_tests.clab_models.test_pip_with_primary_multiplicative import Test_pip_with_Product
from unittest_reinvent.scoring_tests.clab_models.test_clab_top_20 import Test_top_20_base, Test_top_20_acid, \
    Test_top_20_ion_class
