from unittest_reinvent.scoring_tests.physchem.test_mw_score_no_transformation import TestMwScoreNoTransformation
from unittest_reinvent.scoring_tests.physchem.test_mw_score_with_double_sigmoid import TestMwScoreWithDoubleSigmoid
from unittest_reinvent.scoring_tests.physchem.test_num_aliphatic_rings import TestNumAliphaticRingsScoreNoTransformation
from unittest_reinvent.scoring_tests.physchem.test_num_aromatic_rings import TestNumAromaticRingsScoreWithDoubleSigmoid
from unittest_reinvent.scoring_tests.physchem.test_tpsa_score_no_transformation import TestTpsaScoreNoTransformation
from unittest_reinvent.scoring_tests.physchem.test_tpsa_score_with_double_sigmoid import TestTpsaScoreWithDoubleSigmoid
from unittest_reinvent.scoring_tests.physchem.test_hbd_lipinski_score_no_transformation import \
    TestHbdScoreNoTransformation
from unittest_reinvent.scoring_tests.physchem.test_hbd_lipinski_score_with_double_sigmoid import \
    TestHbdScoreWithDoubleSigmoid
from unittest_reinvent.scoring_tests.physchem.test_hba_lipinski_score_no_transformation import \
    TestHbaScoreNoTransformation
from unittest_reinvent.scoring_tests.physchem.test_hba_lipinski_score_with_double_sigmoid import \
    TestHbaScoreWithDoubleSigmoid
from unittest_reinvent.scoring_tests.physchem.test_num_rings_score_no_transformation import \
    TestNumRingsScoreNoTransformation
from unittest_reinvent.scoring_tests.physchem.test_num_rings_score_with_double_sigmoid import \
    TestNumRingsScoreWithDoubleSigmoid
from unittest_reinvent.scoring_tests.physchem.test_slogp_score_no_transformation import TestSlogpScoreNotransformation
from unittest_reinvent.scoring_tests.physchem.test_slogp_score_with_double_sigmoid import \
    TestSlogpScoreWithDoubleSigmoid
from unittest_reinvent.scoring_tests.physchem.test_graph_length_score_no_transformation import \
    TestGraphLengthScoreNoTransformation
from unittest_reinvent.scoring_tests.physchem.test_graph_length_score_with_double_sigmoid import \
    TestGraphLengthScoreWithDoubleSigmoid
from unittest_reinvent.scoring_tests.physchem.test_number_of_stereo_centers import TestNumberOfStereoCenters
from unittest_reinvent.scoring_tests.physchem.test_num_rot_bonds_score_no_transformation import \
    TestNumRotBondsScoreNoTransformation
from unittest_reinvent.scoring_tests.physchem.test_num_rot_bonds_score_with_double_sigmoid import \
    TestNumRotBondsScoreWithDoubleSigmoid
