from unittest_reinvent.scoring_tests.scoring_functions.test_custom_sum import Test_custom_sum
from unittest_reinvent.scoring_tests.scoring_functions.test_custom_sum_combined_distance_and_similarity import \
    TestCombinedDistanceAndSimilarity
from unittest_reinvent.scoring_tests.scoring_functions.test_custom_sum_alerts_with_user_alerts import \
    TestCustomAlertsWithUserAlerts
from unittest_reinvent.scoring_tests.scoring_functions.test_custom_sum_custom_alerts_with_default_alerts import \
    TestCustomAlertsWithDefaultAlerts
from unittest_reinvent.scoring_tests.scoring_functions.test_custom_sum_jaccard_distance import TestJaccardDistance
from unittest_reinvent.scoring_tests.scoring_functions.test_custom_sum_matching_substructure import \
    TestMatchingSubstructures
from unittest_reinvent.scoring_tests.scoring_functions.test_custom_sum_invalid_matching_substructure import \
    TestInvalidMatchingSubstructure
from unittest_reinvent.scoring_tests.scoring_functions.test_custom_sum_matching_substructure_not_provided import \
    TestMatchingSubstructuresNotProvided
from unittest_reinvent.scoring_tests.scoring_functions.test_custom_sum_qed_score import Test_custom_sum_qed_score
from unittest_reinvent.scoring_tests.scoring_functions.test_custom_sum_tanimoto_similarity import \
    TestTanimotoSimilarity
from unittest_reinvent.scoring_tests.scoring_functions.test_parallel_additive import TestParallelAdditive
from unittest_reinvent.scoring_tests.scoring_functions.test_parallel_primary_multiplicative import \
    TestParallelPrimaryMultiplicativeFunction
from unittest_reinvent.scoring_tests.scoring_functions.test_parallel_product import TestParallelProduct
from unittest_reinvent.scoring_tests.scoring_functions.test_parallel_scoring_function_factory import \
    TestParallelScoringFunctionFactory
from unittest_reinvent.scoring_tests.scoring_functions.test_parallel_selectivity_multiplicative import \
    TestParallelSelectivityMultiplicativeFunction
from unittest_reinvent.scoring_tests.scoring_functions.test_primary_mult_with_prediction_classification_and_regression \
    import TestPrimaryMultWithPredictionClassificationAndRegressionAlert
from unittest_reinvent.scoring_tests.scoring_functions.test_primary_multiplicative_with_desirability_component import \
    TestPrimaryMultiplicativeWithDesirabilityComponent
from unittest_reinvent.scoring_tests.scoring_functions.test_primary_multiplicative_function import \
    TestPrimaryMultiplicativeFunction
from unittest_reinvent.scoring_tests.scoring_functions.test_primary_mult_with_no_activity import \
    TestPrimaryMultWithNoActivity
from unittest_reinvent.scoring_tests.scoring_functions.test_primary_multiplicative_with_alert import \
    TestPrimaryMultiplicativeWithAlert
from unittest_reinvent.scoring_tests.scoring_functions.test_primary_mult_with_alert_no_sigm_trans import \
    TestPrimaryMultWithAlertNoSigmTrans
from unittest_reinvent.scoring_tests.scoring_functions.test_product import Test_product
from unittest_reinvent.scoring_tests.scoring_functions.test_score_transformations import Test_score_transformations
from unittest_reinvent.scoring_tests.scoring_functions.test_scoring_function_factory import \
    Test_scoring_function_factory
from unittest_reinvent.scoring_tests.scoring_functions.test_selectivity_multiplicative import \
    Test_selectivity_multiplicative_function, Test_selectivity_multiplicative_function_with_predictive_property, \
    Test_selectivity_multiplicative_function_with_predictive_property_and_alert, \
    Test_selectivity_multiplicative_function_with_predictive_property_no_sigm_trans
from unittest_reinvent.scoring_tests.scoring_functions.test_selectivity_multiplicative_double_sigmoid import \
    Test_desirability_multiplicative_function, Test_selectivity_function_with_double_sigmoid, \
    Test_special_desirability_multiplicative_function
